// <auto-generated />
using System;
using CrewService.Persistance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrewService.Persistance.Data.Migrations.CrewAssignment
{
    [DbContext(typeof(CrewAssignmentDbContext))]
    [Migration("20240914011113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CrewService.Domain.Models.Parents.Parent", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.Railroad", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RailroadMark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCtrlNbr");

                    b.ToTable("Railroads");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Parents.Parent", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("ParentCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("ParentCtrlNbr");

                            b1.ToTable("Parents");

                            b1.WithOwner()
                                .HasForeignKey("ParentCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("ParentCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("ParentCtrlNbr");

                            b1.ToTable("Parents");

                            b1.WithOwner()
                                .HasForeignKey("ParentCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.Railroad", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Parents.Parent", null)
                        .WithMany("Railroads")
                        .HasForeignKey("ParentCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RailroadCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadCtrlNbr");

                            b1.ToTable("Railroads");

                            b1.WithOwner()
                                .HasForeignKey("RailroadCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RailroadCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadCtrlNbr");

                            b1.ToTable("Railroads");

                            b1.WithOwner()
                                .HasForeignKey("RailroadCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Parents.Parent", b =>
                {
                    b.Navigation("Railroads");
                });
#pragma warning restore 612, 618
        }
    }
}
