// <auto-generated />
using System;
using CrewService.Persistance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrewService.Persistance.Data.Migrations.CrewAssignment
{
    [DbContext(typeof(CrewAssignmentDbContext))]
    [Migration("20260131172304_AddRailroadEmployee")]
    partial class AddRailroadEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CrewService.Domain.Models.ContactTypes.AddressType", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmergencyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("AddressTypes");
                });

            modelBuilder.Entity("CrewService.Domain.Models.ContactTypes.EmailAddressType", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmergencyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("EmailAddressTypes");
                });

            modelBuilder.Entity("CrewService.Domain.Models.ContactTypes.PhoneNumberType", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmergencyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("PhoneNumberTypes");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.Address", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long>("AddressTypeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("EmployeeCtrlNbr");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.EmailAddress", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long>("EmailTypeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("EmployeeCtrlNbr");

                    b.ToTable("EmailAddresses");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.Employee", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowFMLAMarkOff")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CallForOvertime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriversLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("EmploymentStatusCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingState")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarriageStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcessPayroll")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TieUpOffProperty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("SocialSecurityNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.EmployeePriorServiceCredit", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("EmployeePriorServiceCredits");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.PhoneNumber", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallingOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DialOne")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneTypeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("EmployeeCtrlNbr");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employment.EmploymentStatus", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("EmploymentStatuses");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employment.EmploymentStatusHistory", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmploymentStatusCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StatusChangeDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.ToTable("EmploymentStatusHistory");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Parents.Parent", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.Railroad", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RailroadMark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCtrlNbr");

                    b.ToTable("Railroads");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadEmployee", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedPoolsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("RailroadEmployees");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPool", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoolNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("RailroadPools");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPoolEmployee", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadPoolCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("RailroadPoolCtrlNbr");

                    b.ToTable("RailroadPoolEmployees");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPoolPayrollTier", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadPoolCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatePercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeOfDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.HasIndex("RailroadPoolCtrlNbr");

                    b.ToTable("RailroadPoolPayrollTiers");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.Craft", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApproveAllMarkOffs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoMarkUp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CraftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CraftNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CraftPluralName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HoursofService")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarkOffHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarkUpHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumVacationDayTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcessPayroll")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadPoolCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredRestHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnpaidMealPeriodMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VacationAssignmentType")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("Crafts");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.Roster", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CraftCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExtraBoard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OvertimeBoard")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadPayrollDepartmentCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RosterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RosterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RosterPluralName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Training")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.Seniority", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanTrain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LastActiveRoster")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RailroadPoolEmployeeCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RosterCtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RosterDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CtrlNbr");

                    b.ToTable("Seniority");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.SeniorityState", b =>
                {
                    b.Property<long>("CtrlNbr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CutBack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Inactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CtrlNbr");

                    b.ToTable("SeniorityStates");
                });

            modelBuilder.Entity("CrewService.Domain.Models.ContactTypes.AddressType", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("AddressTypeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("AddressTypeCtrlNbr");

                            b1.ToTable("AddressTypes");

                            b1.WithOwner()
                                .HasForeignKey("AddressTypeCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("AddressTypeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("AddressTypeCtrlNbr");

                            b1.ToTable("AddressTypes");

                            b1.WithOwner()
                                .HasForeignKey("AddressTypeCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.ContactTypes.EmailAddressType", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("EmailAddressTypeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmailAddressTypeCtrlNbr");

                            b1.ToTable("EmailAddressTypes");

                            b1.WithOwner()
                                .HasForeignKey("EmailAddressTypeCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("EmailAddressTypeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmailAddressTypeCtrlNbr");

                            b1.ToTable("EmailAddressTypes");

                            b1.WithOwner()
                                .HasForeignKey("EmailAddressTypeCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.ContactTypes.PhoneNumberType", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("PhoneNumberTypeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("PhoneNumberTypeCtrlNbr");

                            b1.ToTable("PhoneNumberTypes");

                            b1.WithOwner()
                                .HasForeignKey("PhoneNumberTypeCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("PhoneNumberTypeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("PhoneNumberTypeCtrlNbr");

                            b1.ToTable("PhoneNumberTypes");

                            b1.WithOwner()
                                .HasForeignKey("PhoneNumberTypeCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.Address", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Employees.Employee", null)
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("AddressCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("AddressCtrlNbr");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("AddressCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("AddressCtrlNbr");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.EmailAddress", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Employees.Employee", null)
                        .WithMany("EmailAddresses")
                        .HasForeignKey("EmployeeCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("EmailAddressCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmailAddressCtrlNbr");

                            b1.ToTable("EmailAddresses");

                            b1.WithOwner()
                                .HasForeignKey("EmailAddressCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("EmailAddressCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmailAddressCtrlNbr");

                            b1.ToTable("EmailAddresses");

                            b1.WithOwner()
                                .HasForeignKey("EmailAddressCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.Employee", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("EmployeeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeCtrlNbr");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("EmployeeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeCtrlNbr");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.EmployeePriorServiceCredit", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("EmployeePriorServiceCreditCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeePriorServiceCreditCtrlNbr");

                            b1.ToTable("EmployeePriorServiceCredits");

                            b1.WithOwner()
                                .HasForeignKey("EmployeePriorServiceCreditCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("EmployeePriorServiceCreditCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeePriorServiceCreditCtrlNbr");

                            b1.ToTable("EmployeePriorServiceCredits");

                            b1.WithOwner()
                                .HasForeignKey("EmployeePriorServiceCreditCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.PhoneNumber", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Employees.Employee", null)
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("EmployeeCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("PhoneNumberCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("PhoneNumberCtrlNbr");

                            b1.ToTable("PhoneNumbers");

                            b1.WithOwner()
                                .HasForeignKey("PhoneNumberCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("PhoneNumberCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("PhoneNumberCtrlNbr");

                            b1.ToTable("PhoneNumbers");

                            b1.WithOwner()
                                .HasForeignKey("PhoneNumberCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employment.EmploymentStatus", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("EmploymentStatusCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmploymentStatusCtrlNbr");

                            b1.ToTable("EmploymentStatuses");

                            b1.WithOwner()
                                .HasForeignKey("EmploymentStatusCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("EmploymentStatusCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmploymentStatusCtrlNbr");

                            b1.ToTable("EmploymentStatuses");

                            b1.WithOwner()
                                .HasForeignKey("EmploymentStatusCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employment.EmploymentStatusHistory", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("EmploymentStatusHistoryCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmploymentStatusHistoryCtrlNbr");

                            b1.ToTable("EmploymentStatusHistory");

                            b1.WithOwner()
                                .HasForeignKey("EmploymentStatusHistoryCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("EmploymentStatusHistoryCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmploymentStatusHistoryCtrlNbr");

                            b1.ToTable("EmploymentStatusHistory");

                            b1.WithOwner()
                                .HasForeignKey("EmploymentStatusHistoryCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Parents.Parent", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("ParentCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("ParentCtrlNbr");

                            b1.ToTable("Parents");

                            b1.WithOwner()
                                .HasForeignKey("ParentCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("ParentCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("ParentCtrlNbr");

                            b1.ToTable("Parents");

                            b1.WithOwner()
                                .HasForeignKey("ParentCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.Railroad", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Parents.Parent", null)
                        .WithMany("Railroads")
                        .HasForeignKey("ParentCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RailroadCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadCtrlNbr");

                            b1.ToTable("Railroads");

                            b1.WithOwner()
                                .HasForeignKey("RailroadCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RailroadCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadCtrlNbr");

                            b1.ToTable("Railroads");

                            b1.WithOwner()
                                .HasForeignKey("RailroadCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadEmployee", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RailroadEmployeeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadEmployeeCtrlNbr");

                            b1.ToTable("RailroadEmployees");

                            b1.WithOwner()
                                .HasForeignKey("RailroadEmployeeCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RailroadEmployeeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadEmployeeCtrlNbr");

                            b1.ToTable("RailroadEmployees");

                            b1.WithOwner()
                                .HasForeignKey("RailroadEmployeeCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPool", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RailroadPoolCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadPoolCtrlNbr");

                            b1.ToTable("RailroadPools");

                            b1.WithOwner()
                                .HasForeignKey("RailroadPoolCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RailroadPoolCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadPoolCtrlNbr");

                            b1.ToTable("RailroadPools");

                            b1.WithOwner()
                                .HasForeignKey("RailroadPoolCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPoolEmployee", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Railroads.RailroadPool", null)
                        .WithMany("PoolEmployees")
                        .HasForeignKey("RailroadPoolCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RailroadPoolEmployeeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadPoolEmployeeCtrlNbr");

                            b1.ToTable("RailroadPoolEmployees");

                            b1.WithOwner()
                                .HasForeignKey("RailroadPoolEmployeeCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RailroadPoolEmployeeCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadPoolEmployeeCtrlNbr");

                            b1.ToTable("RailroadPoolEmployees");

                            b1.WithOwner()
                                .HasForeignKey("RailroadPoolEmployeeCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPoolPayrollTier", b =>
                {
                    b.HasOne("CrewService.Domain.Models.Railroads.RailroadPool", null)
                        .WithMany("PayrollTiers")
                        .HasForeignKey("RailroadPoolCtrlNbr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RailroadPoolPayrollTierCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadPoolPayrollTierCtrlNbr");

                            b1.ToTable("RailroadPoolPayrollTiers");

                            b1.WithOwner()
                                .HasForeignKey("RailroadPoolPayrollTierCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RailroadPoolPayrollTierCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RailroadPoolPayrollTierCtrlNbr");

                            b1.ToTable("RailroadPoolPayrollTiers");

                            b1.WithOwner()
                                .HasForeignKey("RailroadPoolPayrollTierCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.Craft", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("CraftCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("CraftCtrlNbr");

                            b1.ToTable("Crafts");

                            b1.WithOwner()
                                .HasForeignKey("CraftCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("CraftCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("CraftCtrlNbr");

                            b1.ToTable("Crafts");

                            b1.WithOwner()
                                .HasForeignKey("CraftCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.Roster", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("RosterCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RosterCtrlNbr");

                            b1.ToTable("Rosters");

                            b1.WithOwner()
                                .HasForeignKey("RosterCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("RosterCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("RosterCtrlNbr");

                            b1.ToTable("Rosters");

                            b1.WithOwner()
                                .HasForeignKey("RosterCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.Seniority", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("SeniorityCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("SeniorityCtrlNbr");

                            b1.ToTable("Seniority");

                            b1.WithOwner()
                                .HasForeignKey("SeniorityCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("SeniorityCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("SeniorityCtrlNbr");

                            b1.ToTable("Seniority");

                            b1.WithOwner()
                                .HasForeignKey("SeniorityCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Seniority.SeniorityState", b =>
                {
                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "CreatedBy", b1 =>
                        {
                            b1.Property<long>("SeniorityStateCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("SeniorityStateCtrlNbr");

                            b1.ToTable("SeniorityStates");

                            b1.WithOwner()
                                .HasForeignKey("SeniorityStateCtrlNbr");
                        });

                    b.OwnsOne("CrewService.Domain.ValueObjects.AuditStamp", "ModifiedBy", b1 =>
                        {
                            b1.Property<long>("SeniorityStateCtrlNbr")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AuditDateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuditName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("SeniorityStateCtrlNbr");

                            b1.ToTable("SeniorityStates");

                            b1.WithOwner()
                                .HasForeignKey("SeniorityStateCtrlNbr");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Employees.Employee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("EmailAddresses");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Parents.Parent", b =>
                {
                    b.Navigation("Railroads");
                });

            modelBuilder.Entity("CrewService.Domain.Models.Railroads.RailroadPool", b =>
                {
                    b.Navigation("PayrollTiers");

                    b.Navigation("PoolEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
