<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-CrewService.BlazorUI-f88e1a94-afff-4beb-ba74-90f4a3ef5934</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrewService.BlazorUI.Client\CrewService.BlazorUI.Client.csproj" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="Google.Api.CommonProtos" Version="2.17.0" />
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.78.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.5" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.83.1" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\Protos\account.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\address_type.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\auth.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\bootstrap.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\common.proto" GrpcServices="None" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\craft.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\email_address_type.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\employee.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\employment_status.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\employment_status_history.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\invitation.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\parent.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\payroll_tier.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\phone_number_type.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\prior_service_credit.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\roster.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\seniority.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\seniority_state.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\user_parent_assignment.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
        <Protobuf Include="..\..\Protos\modules\authorization.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\tenant_config.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\work_management.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\department.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\crews.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\assignments.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\boards.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\roster_board.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\audit_log.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\bulletins.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\policies.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\dispatching.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\absence_vacancy.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\payroll.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\fra_compliance.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\daily_operations.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
    <Protobuf Include="..\..\Protos\modules\qualifications.proto" GrpcServices="Client" ProtoRoot="..\..\Protos" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="Middleware\" />
  </ItemGroup>


</Project>
